version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: 123456789
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql